#!/usr/bin/env bash
# nyan-frames.sh

frames=('=^..^=' '=^-.-^=' '>^.^<' '=^~.~^=' '>^o^<' '=^o.o^=')

messages=(
  "Cute human"
  "Purr for you"
  "Meow motivation"
  "Let's code together"
  "Good job Rizvy"
  "Time to shine"
  "Hug time soon"
  "You're my hero"
  "Keep purring"
  "Soft focus mode"
  "Kitty believes"
  "Sweet human"
  "Paws up!"
  "Love you meow"
  "Little steps big wins"
  "Purr or code?"
  "Meow means focus"
  "Cute but lazy"
  "Chop chop cutie"
  "Hustle my love"
  "Lazy cutie"
  "Purr harder baby"
  "Sweet but slow"
  "Focus pretty human"
  "Kitty is judging"
  "Code for meow"
  "Good human... almost"
  "Paws up Rizvy"
  "Love you cutie"
  "Slacker with charm"
  "Meow my star"
  "Soft hustle mode"
  "You're my purrfect"
  "Keep going baby"
  "Tiny steps hero"
  "Purr time Rizvy"
  "Sweet lazy human"
  "Meow means work"
  "Cute legend"
  "Focus my love"
  "Purr harder Rizvy"
  "Kitty says code"
  "Good job cutie"
  "Lazy but cute"
  "Time to purr"
  "Hug your code"
  "Sweet focus mode"
  "Paws up hero"
  "Meow motivation Rizvy"
  "You're my baby"
  "Chop chop meow"
  "Little wins today"
  "Purr for Rizvy"
  "Soft human mode"
  "Keep shining cutie"
  "Meow or move"
  "Cute hustle mode"
  "Love you star"
  "Kitty believes in you"
  "Purr harder love"
  "Sweet code time"
  "Lazy hero"
  "Focus cutie pie"
  "Paws up baby"
  "Meow means try"
  "Good job my human"
  "Time to build"
  "You're awesome meow"
  "Soft steps forward"
  "Purrfect human"
  "Hustle sweet Rizvy"
  "Kitty is proud"
  "Cute but coding"
  "Love you more"
  "Meow focus now"
  "Little purr big win"
  "Sweet slacker"
  "Purr time soon"
  "You're my cutie"
  "Chop chop Rizvy"
  "Keep purring hero"
  "Soft but strong"
  "Meow my genius"
  "Lazy legend"
  "Focus for meow"
  "Purr harder star"
  "Good human vibes"
  "Time to glow"
  "Hug time Rizvy"
  "Sweet meow motivation"
  "Paws up cutie"
  "Love you baby"
  "Kitty says yes"
  "Cute focus mode"
  "Meow means magic"
  "You're my fluffy"
  "Little steps cutie"
  "Purr or hustle"
  "Sweet human alert"
  "Keep going my love"
  "Purrfect code time"
  "Lazy but lovely"
  "Meow motivation boost"
  "Focus pretty Rizvy"
  "You're my champ"
  "Soft purr mode"
  "Chop chop baby"
  "Good job hero"
  "Love you meow meow"
  "Kitty believes hard"
  "Cute hustle baby"
  "Time to sparkle"
  "Purr for wins"
  "Sweet but sassy"
  "Meow means build"
  "Paws up star"
  "Lazy cute human"
  "Keep shining Rizvy"
  "You're my everything"
  "Purr harder cutie"
  "Little wins meow"
  "Sweet focus Rizvy"
  "Meow or code"
  "Good job my star"
  "Hug your dreams"
  "Kitty is happy"
  "Cute but focused"
  "Love you always"
  "Soft legend mode"
  "Purr time hero"
  "Meow motivation time"
  "You're my baby hero"
  "Chop chop love"
  "Keep purring cutie"
  "Sweet code vibes"
  "Paws up my love"
  "Lazy genius"
  "Focus mode activated"
  "Purr for Rizvy"
  "Meow means success"
  "Good human today"
  "Time to win"
  "You're purrfect"
  "Little steps big meow"
  "Sweet slacker alert"
  "Hustle my cutie"
  "Kitty loves you"
  "Cute but coding hard"
  "Love you star"
  "Purr harder baby"
  "Soft human shine"
  "Meow focus cutie"
  "Paws up legend"
  "Good job my purr"
  "Time to meow"
  "You're my motivation"
  "Keep going sweet"
  "Lazy but trying"
  "Purr or shine"
  "Cute code hero"
  "Meow means love"
  "Sweet focus baby"
  "Chop chop star"
  "Purrfect little steps"
  "Love you Rizvy"
  "Kitty is cheering"
  "Soft but fierce"
  "Meow motivation hero"
  "Good job cutie pie"
  "Time to hug code"
  "You're my fluffy hero"
  "Purr harder love"
  "Little wins Rizvy"
  "Sweet human glow"
  "Paws up baby"
  "Meow or magic"
  "Keep purring star"
  "Cute hustle mode"
  "Love you meow"
  "Lazy cute legend"
  "Focus my everything"
  "Purr time cutie"
  "Good job my love"
  "Time to sparkle Rizvy"
  "You're my soft hero"
  "Kitty believes forever"
  "Sweet but strong"
  "Meow means try harder"
  "Purr for wins Rizvy"
  "Chop chop my star"
  "Little steps my baby"
  "Love you purrfect"
  "Soft focus legend"
  "Meow motivation cutie"
  "Good human meow"
  "Paws up forever"
  "Keep shining baby"
  "Cute but unstoppable"
  "Purr harder my hero"
  "Love you always Rizvy"
)

# Pick a sleep frame based on an 6 element animation cycling every 1 second
current_sec=$(date +%s)
frame_i=$(( current_sec % 6 ))
remainder=$(( current_sec % 180 ))

if [ $remainder -lt 30 ]; then
  msg_i=$(( (current_sec / 180) % ${#messages[@]} ))
  echo "${frames[$frame_i]}   ${messages[$msg_i]}"
else
  echo "${frames[$frame_i]}"
fi