preload = /home/devrizvy/Pictures/reze.png
preload = /home/devrizvy/Pictures/maindisplay.png

wallpaper = DP-3,/home/devrizvy/Pictures/reze.png
wallpaper = HDMI-A-1,/home/devrizvy/Pictures/maindisplay.png